### ISSUE TITLE
gPSP launch command

### ISSUE THREAD

**Issue by Ryan86me** [dragoonDorise/pegasus-rp2-metadata#1]
I can actually contribute to something! Found this through endless tinkering a while back:

launch: am start --user 0
  -n com.gpsp/com.retroarch.browser.retroactivity.RetroActivityFuture
  -e ROM {file.path}
  -e LIBRETRO /data/data/com.gpsp/cores/gpsp_libretro_android.so
  -e CONFIGFILE /storage/emulated/0/Android/data/com.gpsp/files/retroarch.cfg
  -e IME com.android.inputmethod.latin/.LatinIME
  -e DATADIR /data/data/com.gpsp
  -e APK /data/app/com.gpsp-1/base.apk
  -e SDCARD /mnt/media_rw/1234567890
  -e EXTERNAL /storage/emulated/0/Android/data/com.gpsp/files
  --activity-clear-top

**Comment by dragoonDorise** [comment]
Thank U @Ryan86me , works like a charm!

PS: For SD Formatted as internal you need to change the SDCARD route: 

-e SDCARD /storage/emulated/0
