### ISSUE TITLE
N64 Launch Command

### ISSUE THREAD

**Issue by danielthewise** [dragoonDorise/pegasus-rp2-metadata#2]
Trying to launch N64 games with the given command just sends me to a black screen for a while, then back to the Pegasus menu. Is there something I'm missing?

**Comment by dragoonDorise** [comment]
I'm working on it!

**Comment by dragoonDorise** [comment]
Hi @danielthewise , i've uploaded a new version of the metadata for all the systems, N64 works now!

Keep in mind you need to have the roms in z64, n64 or v64 extensions, as Mupen doesn't seem to like zipped roms.

I've also updated the Guide in the readme, check it out: https://github.com/dragoonDorise/pegasus-rp2-metadata

**Comment by danielthewise** [comment]
That's awesome! Thanks!
