### ISSUE TITLE
More systems support

### ISSUE THREAD

**Issue by XargonWan** [dragoonDorise/pegasus-rp2-metadata#3]
Can you please add the following systems?

DOOM (prboom .wads)
DOS (DosBox .config)
Final Burn Alpha
Gameboy Color
Neo Geo CD
Neo Geo Pocket
Neo Geo Pocket Color
Nintendo - Game and Watch
Pokemon Mini
Sega Game Gear
Wonderswan
Wonderswan Color

Thanks a lot in advance!

**Comment by dragoonDorise** [comment]
Hi @XargonWan , I've uploaded a new update, I've added all the systems but the Game and Watch one, can you confirm if you can load Game and Watch roms using the Mame4droid App that comes with the RP2? Thanks!
